insert into country (id, name, code_name) values (0, 'Australia', 'AU');
insert into country (id, name, code_name) values (1, 'Canada', 'CA');
insert into country (id, name, code_name) values (2, 'France', 'FR');
insert into country (id, name, code_name) values (3, 'Hong Kong', 'HK');
insert into country (id, name, code_name) values (4, 'Iceland', 'IC');
insert into country (id, name, code_name) values (5, 'Japan', 'JP');
insert into country (id, name, code_name) values (6, 'Nepal', 'NP');
insert into country (id, name, code_name) values (7, 'Russian Federation', 'RU');
insert into country (id, name, code_name) values (8, 'Sweden', 'SE');
insert into country (id, name, code_name) values (9, 'Switzerland', 'CH');
insert into country (id, name, code_name) values (10, 'United Kingdom', 'GB');
insert into country (id, name, code_name) values (11, 'United States', 'US');